apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels: # kv-pair for k8s components
    app: mongo
spec: # deployment specification
  replicas: 1 # how many pod(s) to create
  selector: # decide which pods belong to this deployment
    matchLabels:
      app: mongo
  template: # configuration for pod
    metadata:
      labels:
        app: mongo
    spec:
      containers: # list of containers , define image and port 
      - name: mongodb
        image: mongo:5.0
        ports:
        - containerPort: 27017
        env: 
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret  # name of Secret
              key: mongo-user     # key of the Secret
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password
--- # YAML syntax for next configuration

apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017 # containerPort of Deployment
